version: '3'


services: 
    db:
        image: postgres:12
        container_name: dj3_db
        restart: always
        volumes:
            - pg_data:/var/lib/postgresql/data
            #- pg_data:./data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_DB=hot_news
            - POSTGRES_PASSWORD=abcd1234
    web:
        #build: ./web
        build: ./Project_hot_news_api
        container_name: dj3_web
        restart: always
        #command: [ "wait-for-it.sh", "db:5432", "--", "/bin/bash", "-c", "uwsgi --ini uwsgi.ini" ]
        command: [ "/bin/bash", "-c", "uwsgi --ini uwsgi.ini" ]
        volumes:
            # Using for production that could share the named volume for other services.
            #- web_data:/web/dj3
            - web_data:/Project_hot_news_api/hot_news_project
        environment:
            - PYTHONUNBUFFERED=TURE
            - DATABASE_NAME=hot_news
            - DATABASE_USER=postgres
            - POSTGRES_PASSWORD=abcd1234
            - DB_HOST=db

    nginx:
        build: /usr/local/etc/nginx
        container_name: dj3_nginx
        restart: always
        volumes:
            # Using the named volume from the Django project.
            #- web_data:/web/dj3
            - web_data:/Project_hot_news_api/hot_news_project
            # Bind the nginx's log into host machine.
            - /usr/local/etc/nginx/logs:/var/log/nginx
        ports:
            - "127.0.0.1:8000:80"
        depends_on:
            - web

volumes:
    web_data:
    pg_data: {}