# Generated by Django 3.2 on 2022-03-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_id', models.CharField(default='', max_length=30, verbose_name='網址')),
                ('title', models.CharField(default='', max_length=200, verbose_name='標題')),
                ('date', models.DateField(verbose_name='日期')),
                ('content', models.TextField(verbose_name='內文')),
            ],
            options={
                'verbose_name': '熱門新聞',
                'verbose_name_plural': '熱門新聞',
            },
        ),
    ]
