FROM python:3.7
LABEL maintainer="oo.vivian@hotmail.com"

ENV PYTHONUNBUFFERED 1

#RUN mkdir /hot_news_project
WORKDIR /hot_news_project
COPY . /hot_news_project


RUN pip install -r requirements.txt

WORKDIR  /hot_news_project
